apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: e-sketch-tls-certificate
  namespace: istio-system
spec:
  secretName: e-sketch-tls-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: e-sketch.ru
  dnsNames:
    - e-sketch.ru