apiVersion: v1
kind: Service
metadata:
  name: est-mono
  namespace: est-units
spec:
  selector:
    app: est-mono
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
