---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-proxy
  namespace: est-units
  labels:
    app: est-proxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: est-proxy
  template:
    metadata:
      name: est-proxy
      labels:
        app: est-proxy
    spec:
      containers:
        - name: est-proxy
          image: ghcr.io/umu-art/est-proxy:master
          imagePullPolicy: Always

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000

          env:
            - name: ELASTIC_APM_SERVER_URL
              value: http://apm-server.est-monitoring.svc.cluster.local:8200
            - name: ELASTIC_APM_SERVICE_NAME
              value: est-proxy
            - name: ELASTIC_APM_ENVIRONMENT
              value: est
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: password
                  optional: false

          resources:
            requests:
              memory: "100M"
              cpu: "100m"
            limits:
              memory: "200M"
              cpu: "200m"

          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          livenessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
