---
apiVersion: v1
kind: Service
metadata:
  name: est-proxy
  namespace: est-units
spec:
  selector:
    app: est-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
