---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-preview
  namespace: e-sketch
  labels:
    app: est-preview
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: est-preview
  template:
    metadata:
      name: est-preview
      labels:
        app: est-preview
    spec:
      containers:
        - name: est-preview
          image: ghcr.io/umu-art/est-preview:master
          imagePullPolicy: Always

          env:
            - name: REDIS_URL
              value: redis://redis.databases.svc.cluster.local:6379
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kasumi-secrets
                  key: REDIS_PASSWORD

            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: kasumi-secrets
                  key: S3_ENDPOINT
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: kasumi-secrets
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: kasumi-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: kasumi-secrets
                  key: S3_BUCKET_NAME

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: "100M"
              cpu: "100m"
            limits:
              memory: "100M"
              cpu: "200m"

          readinessProbe:
            httpGet:
              path: /actuator
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20

          livenessProbe:
            httpGet:
              path: /actuator
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
