---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-preview
  namespace: e-sketch
  labels:
    app: est-preview
spec:
  revisionHistoryLimit: 1
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: est-preview
  template:
    metadata:
      name: est-preview
      labels:
        app: est-preview
    spec:
      containers:
        - name: est-preview
          image: ghcr.io/umu-art/est-preview:master
          imagePullPolicy: Always

          env:
            - name: REDIS_URL
              value: redis://redis-master.redis.svc.cluster.local:6379
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases-credentials
                  key: REDIS_PASSWORD

            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: e-sketch-s3-credentials
                  key: S3_URL
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: e-sketch-s3-credentials
                  key: S3_ACCESS
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: e-sketch-s3-credentials
                  key: S3_SECRET
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: e-sketch-s3-credentials
                  key: S3_BUCKET

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: "100M"
              cpu: "100m"
            limits:
              memory: "100M"
              cpu: "100m"

          readinessProbe:
            httpGet:
              path: /actuator
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
