---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-preview
  namespace: e-sketch
  labels:
    app: est-preview
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: est-preview
  template:
    metadata:
      name: est-preview
      labels:
        app: est-preview
    spec:
      containers:
        - name: est-preview
          image: ghcr.io/umu-art/est-preview:master
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: "50M"
              cpu: "100m"
            limits:
              memory: "100M"
              cpu: "200m"

          readinessProbe:
            httpGet:
              path: /actuator
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20

          livenessProbe:
            httpGet:
              path: /actuator
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
