---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-front
  namespace: est-units
  labels:
    app: est-front
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: est-front
  template:
    metadata:
      name: est-front
      labels:
        app: est-front
    spec:
      containers:
        - name: est-front
          image: ghcr.io/umu-art/est-front:master
          imagePullPolicy: Always

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000

          resources:
            requests:
              memory: "100M"
              cpu: "50m"
            limits:
              memory: "200M"
              cpu: "100m"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
