apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: est-dbs
  labels:
    app: rabbit
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      name: rabbit
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: dockerhub.timeweb.cloud/rabbitmq:3-management
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000

          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin

            - name: RABBITMQ_DEFAULT_PASS
              value: admin

            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbit disk_free_limit 2147483648

          resources:
            requests:
              memory: "300M"
              cpu: "100m"
            limits:
              memory: "600M"
              cpu: "200m"

      restartPolicy: Always
      