apiVersion: v1
kind: PersistentVolume
metadata:
  name: est-pg-pv
  labels:
    type: local
    app: est-pg
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/est-pg-db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: est-pg-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
