apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: est-monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 0

      containers:
        - name: grafana
          image: grafana/grafana:10.4.1
          imagePullPolicy: Always

          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources/all.yaml
              name: grafana-datasources-config

          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000

          resources:
            requests:
              memory: "200M"
              cpu: "100m"
            limits:
              memory: "400M"
              cpu: "200m"

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2

          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasources-config
          configMap:
            name: grafana-datasources-config

      restartPolicy: Always
      