---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: est-monitoring
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200

    - name: transport
      port: 9300
