name: "Deploy to stand"
description: "Доставка образа на стенд, синхронизация и ожидание успешного запуска"

inputs:
  kubesecret:
    description: "kubesecret"
    required: true
  module-name:
    description: "Модуль для синхронизации"
    required: true
  argocd-server:
    description: "ArgoCD url"
    required: true
  argocd-token:
    description: "Токен ArgoCD"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set the Kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.kubesecret }}

    - name: Deploy ${{ inputs.module-name }}
      shell: bash
      run: kubectl rollout restart deployment/${{ inputs.module-name }} -n e-sketch

    - uses: clowdhaus/argo-cd-action/@main
      with:
        version: 2.6.7
        options: --server ${{ inputs.argocd-server }} --grpc-web --auth-token ${{ inputs.argocd-token }}
        command: app sync e-sketch --resource :Deployment:${{ inputs.module-name }} --prune --timeout 300

    - uses: clowdhaus/argo-cd-action/@main
      with:
        version: 2.6.7
        options: --server ${{ inputs.argocd-server }} --grpc-web --auth-token ${{ inputs.argocd-token }}
        command: app wait e-sketch --resource :Deployment:${{ inputs.module-name }} --health --timeout 300

