---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  labels:
    type: db
spec:
  destination:
    namespace: est-dbs
    server: https://kubernetes.default.svc
  project: e-sketch
  source:
    path: iac/kubernetes/est-dbs/postgres
    repoURL: git@github.com:umu-art/e-sketch.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
