---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e-sketch
  namespace: argocd
  labels:
    type: unit
spec:
  destination:
    namespace: e-sketch
    server: https://kubernetes.default.svc
  source:
    path: iac/kubernetes
    repoURL: git@github.com:umu-art/KasumiHeart.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
