---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e-sketch-mono
  namespace: argocd
  labels:
    type: unit
spec:
  destination:
    namespace: e-sketch
    server: https://kubernetes.default.svc
  source:
    path: iac/kubernetes-tmp/est-mono
    repoURL: git@github.com:umu-art/e-sketch.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
