---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-back
  namespace: est-units
  labels:
    app: est-back
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: est-back
  template:
    metadata:
      name: est-back
      labels:
        app: est-back
    spec:
      containers:
        - name: est-back
          image: ghcr.io/umu-art/est-back:master
          imagePullPolicy: Always

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000

          resources:
            requests:
              memory: "200M"
              cpu: "100m"
            limits:
              memory: "400M"
              cpu: "200m"

          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
