---
apiVersion: v1
kind: Service
metadata:
  name: est-back
  namespace: est-units
spec:
  selector:
    app: est-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
