name: "Prepare env"
description: "Подготовка окружения для пайпы, установка java, node, go"

inputs:
  cacheTag:
    description: cacheTag
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js 21
      uses: actions/setup-node@v4.0.4
      with:
        node-version: 21
        cache: 'npm'
        cache-dependency-path: |
          est-front/package-lock.json

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Setup Go environment
      uses: actions/setup-go@v5.2.0
      with:
        go-version: 1.23.0
        cache: true
        cache-dependency-path: |
          est-proxy/go.sum

    - name: Restore api cache
      id: api-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: api/build
        key: ${{ inputs.cacheTag }}

    - name: Build API
      if: steps.api-cache-restore.outputs.cache-hit != 'true'
      working-directory: ./api
      shell: bash
      run: chmod +x ./build.sh && ./build.sh

    - name: Save api cache
      if: steps.api-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: api/build
        key: ${{ inputs.cacheTag }}