name: "Prepare env"
description: "Подготовка окружения для пайпы, установка java, node, go"
runs:
  using: "composite"
  steps:
  - name: Set up Node.js 21
    uses: actions/setup-node@v4.0.4
    with:
      node-version: 21

  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '21'

  - name: Setup Go environment
    uses: actions/setup-go@v5.0.2
    with:
      go-version: 1.23.0
      cache: true
