---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: e-sketch-s3-credentials
  namespace: e-sketch
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: kv
    kind: ClusterSecretStore
  target:
    name: e-sketch-s3-credentials
  data:
    - secretKey: S3_URL
      remoteRef:
        key: e-sketch-secrets
        property: S3_URL
    - secretKey: S3_ACCESS
      remoteRef:
        key: e-sketch-secrets
        property: S3_ACCESS
    - secretKey: S3_SECRET
      remoteRef:
        key: e-sketch-secrets
        property: S3_SECRET
    - secretKey: S3_REGION
      remoteRef:
        key: e-sketch-secrets
        property: S3_REGION
    - secretKey: S3_BUCKET
      remoteRef:
        key: e-sketch-secrets
        property: S3_BUCKET
