scrape_configs:
  - job_name: 'grafana monitor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cashezavr.monitoring']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: [ 'kube-state-metrics.kube-metrics.svc.cluster.local:8080' ]