apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: est-dbs
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: dockerhub.timeweb.cloud/postgres:latest
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000

          env:
            - name: POSTGRES_DB
              value: est-data
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage

          resources:
            requests:
              memory: "300M"
              cpu: "300m"
            limits:
              memory: "600M"
              cpu: "600m"

          readinessProbe:
            exec:
              command:
                - psql
                - -U
                - postgres
                - -c
                - 'select 1'
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            exec:
              command:
                - psql
                - -U
                - postgres
                - -c
                - 'select 1'
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5

      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

      restartPolicy: Always