apiVersion: v1
kind: Service
metadata:
  name: est-mono
  namespace: e-sketch
spec:
  selector:
    app: est-mono
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 8080
  type: ClusterIP
