name: "Build image"
description: "Сборка docker image"

inputs:
  image:
    description: 'Image name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: umu-art
        password: ${{ secrets.PACKAGES_TOKEN }}

    - name: Extract metadata for ${{ inputs.image }}
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ghcr.io/umu-art/${{ inputs.image }}

    - name: Build and push Docker image for ${{ inputs.image }}
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./iac/images/${{ inputs.image }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}