additionalProperties:
  artifactId: est-mono-api
  groupId: ru.est
  basePackage: ru.est.mono
  invokerPackage: ru.est.mono
  apiPackage: ru.est.mono.api
  modelPackage: ru.est.mono.model
  useTags: true
  interfaceOnly: true
  skipDefaultInterface: true
  useSpringBoot3: true
  useJakartaEe: true