apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-rabbit
  namespace: est-dbs
  labels:
    app: est-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: est-rabbit
  template:
    metadata:
      name: est-rabbit
      labels:
        app: est-rabbit
    spec:
      containers:
        - name: est-rabbit
          image: dockerhub.timeweb.cloud/rabbitmq:3-management
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin

            - name: RABBITMQ_DEFAULT_PASS
              value: admin

            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbit disk_free_limit 2147483648

          resources:
            requests:
              memory: "350Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"

      restartPolicy: Always
      