---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  labels:
    app: apm-server
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    
    queue: { }
    
    output.elasticsearch:
      hosts: [ "https://elasticsearch:9200" ]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      protocol: https
      ssl.certificate_authorities:
        - /usr/share/apm-server/config/certs/elastic.crt
