---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: est-monitoring
  labels:
    app: apm-server
spec:
  selector:
    app: apm-server
  ports:
    - port: 8200
      protocol: TCP
      name: http
      targetPort: 8200
  type: ClusterIP
