---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apm-server
  namespace: argocd
  labels:
    type: monitoring
spec:
  destination:
    namespace: est-monitoring
    server: https://kubernetes.default.svc
  project: e-sketch
  source:
    path: iac/kubernetes/est-monitoring/apm-server
    repoURL: git@github.com:umu-art/e-sketch.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
