---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: est-monitoring
  labels:
    app: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000

      volumes:
        - name: kibana-tokens
          emptyDir: { }
        - name: elasticsearch-certs
          secret:
            secretName: elasticsearch-certs

      containers:
        - name: kibana
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000

          image: "dockerhub.timeweb.cloud/kibana:8.14.3"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://elasticsearch:9200"
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: "/usr/share/kibana/config/certs/elastic.crt"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-kibana-es-token
                  key: token
                  optional: false
            - name: NODE_OPTIONS
              value: --max-old-space-size=1800

          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi

          volumeMounts:
            - name: elasticsearch-certs
              mountPath: /usr/share/kibana/config/certs
              readOnly: true

            - name: kibana-tokens
              mountPath: /usr/share/kibana/config/tokens
              readOnly: true