apiVersion: apps/v1
kind: Deployment
metadata:
  name: est-minio
  namespace: est-dbs
  labels:
    app: est-minio
spec:
  selector:
    matchLabels:
      app: est-minio
  template:
    metadata:
      labels:
        app: est-minio
    spec:
      containers:
        - name: est-minio
          image: minio/minio
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin

          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20

          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20

          volumeMounts:
            - name: data
              mountPath: /data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: est-minio-pvc