openapi: 3.1.0

info:
  title: EST Back API
  description: Все запросы от прокси к бэку
  version: 1.0.0

servers:
  - url: 'https://e-sketch.ru'
  - url: 'http://localhost:8080'

security:
  - none: [ ]

paths:

  #################################### Board ####################################

  /back/board/list/{userId}:
    get:
      tags:
        - board
      summary: Получение списка досок
      operationId: listByUserId
      parameters:
        - $ref: "#/components/parameters/UserId"
      responses:
        200:
          description: Список досок
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackBoardListDto"

  /back/board/create/{userId}:
    post:
      tags:
        - board
      summary: Создание доски
      operationId: create
      parameters:
        - $ref: "#/components/parameters/UserId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertBoardDto"
      responses:
        200:
          description: Новая доска
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackBoardDto"

  /back/board/{boardId}:
    get:
      tags:
        - board
      summary: Получение доски по uuid
      operationId: getByUuid
      parameters:
        - $ref: "#/components/parameters/BoardId"
      responses:
        200:
          description: Обновленная доска
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackBoardDto"
    patch:
      tags:
        - board
      summary: Обновление доски
      operationId: update
      parameters:
        - $ref: "#/components/parameters/BoardId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertBoardDto"
      responses:
        200:
          description: Обновленная доска
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackBoardDto"
    delete:
      tags:
        - board
      summary: Удаление доски
      operationId: deleteBoard
      parameters:
        - $ref: "#/components/parameters/BoardId"
      responses:
        200:
          description: Успешное удаление

  /back/board/share/{boardId}:
    post:
      tags:
        - board
      summary: Поделиться доской
      operationId: share
      parameters:
        - $ref: "#/components/parameters/BoardId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BackSharingDto"
      responses:
        200:
          description: Успеха
    patch:
      tags:
        - board
      summary: Обновить доступ к доске
      operationId: updateShare
      parameters:
        - $ref: "#/components/parameters/BoardId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BackSharingDto"
      responses:
        200:
          description: Успеха
    delete:
      tags:
        - board
      summary: Отозвать доступ к доске
      operationId: unshare
      parameters:
        - $ref: "#/components/parameters/BoardId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UnshareBoardDto"
      responses:
        200:
          description: Успеха

  #################################### Figure ####################################
  /back/figure/list/{boardId}:
    get:
      tags:
        - figure
      summary: Получение списка фигур
      operationId: listByBoardId
      parameters:
        - $ref: "#/components/parameters/BoardId"
      responses:
        200:
          description: Список фигур
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FigureListDto"

  /back/figure/create/{boardId}:
    post:
      tags:
        - figure
      summary: Создание фигуры
      operationId: createFigure
      parameters:
        - $ref: "#/components/parameters/BoardId"
      responses:
        200:
          description: Новая фигура
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FigureIdDto"

  /back/figure/{figureId}:
    patch:
      tags:
        - figure
      summary: Обновление фигуры
      operationId: updateFigure
      parameters:
        - $ref: "#/components/parameters/FigureId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FigureDto"
      responses:
        200:
          description: Успешное обновление
    delete:
      tags:
        - figure
      summary: Удаление фигуры
      operationId: deleteFigure
      parameters:
        - $ref: "#/components/parameters/FigureId"
      responses:
        200:
          description: Успешное удаление


components:
  parameters:
    UserId:
      in: path
      name: userId
      required: true
      description: id пользователя
      schema:
        type: string
        format: uuid

    BoardId:
      name: boardId
      in: path
      required: true
      schema:
        type: string
        format: uuid

    FigureId:
      name: figureId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    BackBoardDto:
      required:
        - id
        - name
        - description
        - ownerId
        - sharedWith
        - linkSharedMode
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        ownerId:
          type: string
          format: uuid
        sharedWith:
          type: array
          items:
            $ref: "#/components/schemas/BackSharingDto"
        linkSharedMode:
          $ref: "#/components/schemas/LinkShareMode"

    BackBoardListDto:
      required:
        - mine
        - shared
      properties:
        mine:
          type: array
          items:
            $ref: "#/components/schemas/BackBoardDto"
        shared:
          type: array
          items:
            $ref: "#/components/schemas/BackBoardDto"

    BackSharingDto:
      required:
        - userId
        - access
      properties:
        userId:
          type: string
          format: uuid
        access:
          $ref: "#/components/schemas/ShareMode"

    LinkShareMode:
      type: string
      enum:
        - none_by_link
        - read_by_link
        - write_by_link

    ShareMode:
      type: string
      enum:
        - read
        - write
        - admin

    UpsertBoardDto:
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        linkSharedMode:
          $ref: "#/components/schemas/LinkShareMode"

    UnshareBoardDto:
      required:
        - userId
      properties:
        userId:
          type: string
          format: uuid

    FigureDto:
      required:
        - data
      properties:
        data:
          type: string
          format: binary

    FigureListDto:
      required:
        - figures
      properties:
        figures:
          type: array
          items:
            $ref: "#/components/schemas/FigureDto"

    FigureIdDto:
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
