name: Test all

on:
  pull_request: [ ]

env:
  REGISTRY: ghcr.io

jobs:

  ### Test api: ###

  lint-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 21
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 21

      - name: Install redocly
        run: npm i -g @redocly/cli@latest

      - name: Lint proxy API
        run: cd ./api && npx @redocly/cli@latest lint ./est-proxy-api.yaml --config ./config/lint.yaml

      - name: Lint back API
        run: cd ./api && npx @redocly/cli@latest lint ./est-back-api.yaml --config ./config/lint.yaml

  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare and build Api
        uses: ./.github/workflows/actions/prepare_env
        with:
          cacheTag: api-${{ hashFiles('api/') }}

  ### Test modules: ###

  est-back-test:
    needs: [ lint-api, build-api ]
    uses: ./.github/workflows/est-back-test.yml

  est-proxy-test:
    needs: [ lint-api, build-api ]
    uses: ./.github/workflows/est-proxy-test.yml

  est-preview-test:
    needs: [ lint-api, build-api ]
    uses: ./.github/workflows/est-preview-test.yml

  est-front-test:
    needs: [ lint-api, build-api ]
    uses: ./.github/workflows/est-front-test.yml
