name: est-back-deploy

on:
  push:
    branches: [ "master" ]

env:
  MODULE_NAME: est-back

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare and build Api
        uses: ./.github/workflows/actions/prepare_env
        with:
          cacheTag: api-${{ hashFiles('api/') }}

      - name: Build image
        uses: ./.github/workflows/actions/build_image
        with:
          image: ${{ env.MODULE_NAME }}
          actor: umu-art
          token: ${{ secrets.PACKAGES_TOKEN }}

  deploy:
    needs: [ build-image ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: ./.github/workflows/actions/deploy_to_stand
        with:
          kubesecret: ${{ secrets.KUBESECRET }}
          module-name: ${{ env.MODULE_NAME }}
          argocd-server: ${{ secrets.ARGO_SERVER }}
          argocd-token: ${{ secrets.ARGO_TOKEN }}