name: est-front-test

on:
  workflow_call: { }

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare and build Api
        uses: ./.github/workflows/actions/prepare_env
        with:
          cacheTag: api-${{ hashFiles('api/') }}

      - name: Build libs
        uses: ./.github/workflows/actions/build_libs

      - name: Install deps
        working-directory: ./est-front
        run: npm install

      - name: Test front
        working-directory: ./est-front
        run: npm run test
