name: est-api-test

on:
  pull_request:
    paths:
      - 'api/**'

jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 21
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 21

      - name: Install redocly
        run: npm i -g @redocly/cli@latest

      - name: Lint proxy API
        working-directory: ./api
        run: npx @redocly/cli@latest lint ./est-proxy-api.yaml --config ./config/lint.yaml

      - name: Lint back API
        working-directory: ./api
        run: npx @redocly/cli@latest lint ./est-back-api.yaml --config ./config/lint.yaml

  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare and build Api
        uses: ./.github/workflows/actions/prepare_env
        with:
          cacheTag: api-${{ hashFiles('api/') }}
